### ISSUE TITLE
Does not Login when added.

### ISSUE THREAD

**Issue by Crxaw** [kss342/RoProRex#19]
After adding the "RoProRex" Folder it does not login into to RoPro and leaves you logged out.

**Comment by kss342** [comment]
it will login eventually after using it for 1-2 days, also try updating the extension from this github page

**Comment by kss342** [comment]
no i just understodyour problem, working on fixing it right now

**Comment by Crxaw** [comment]
> no i just understodyour problem, working on fixing it right now

Thanks man, Just wanted to make sure that is was an issue not just how the plugin worked.

**Comment by Crxaw** [comment]
> everything is uptodate now feel free to use it (also star please)

Should push update to main branch link inside of readme.md
